name: Update crate-dist mirror
author: Michał Górny
description: Fetch new upstream tags for a mirror and trigger crate dist builds for them
inputs:
  ssh-private-key:
    description: Private SSH key to use for pushing
    required: true
  directories:
    description: Directories with Cargo.toml files to process
    default: .
  upstream-repo:
    description: URL to fetch upstream repository from (the default is to query GitHub)
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set SSH key up
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Add upstream remote (according to GitHub parent)
      if: ${{ inputs.upstream-repo == '' }}
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        git remote add upstream $(gh repo view ${{ github.repository }} --json parent --template 'https://github.com/{{.parent.owner.login}}/{{.parent.name}}')
    - name: Add upstream remote (explicitly specified)
      if: ${{ inputs.upstream-repo != '' }}
      shell: bash
      run: |
        git remote add upstream ${{ inputs.upstream-repo }}
    - name: Fetch upstream tags
      shell: bash
      run: git ls-remote --sort=refname --refs --tags upstream | awk '{ print $2 }' > upstream-tags.txt
    - name: Fetch our tags
      shell: bash
      run: git ls-remote --sort=refname --refs --tags | awk '{ print $2 }' > our-tags.txt
    - name: Configure git for committing
      shell: bash
      run: |
        git config --global user.email mgorny@gentoo.org
        git config --global user.name gentoo-crate-dist
    - name: Push new tags
      shell: bash
      run: |
        WORKFLOW="
        name: Create crate dist
        on:
          push:
            tags:
              - '*'

        jobs:
          crate-dist:
            runs-on: ubuntu-latest
            permissions:
              contents: write
            steps:
              - name: Create crate dist
                uses: projg2/crate-dist-action@v1
                with:
                  directories: ${{ inputs.directories }}
        "
        while read tag; do
          git fetch upstream "${tag}" &&
          git checkout FETCH_HEAD &&
          git rm -rf --ignore-unmatch .github/workflows &&
          mkdir -p .github/workflows &&
          echo "${WORKFLOW}" > .github/workflows/crate-dist.yml &&
          git add .github/workflows/crate-dist.yml &&
          git commit -m "Replace workflows" &&
          git push git@github.com:${{ github.repository }} HEAD:${tag} || exit 1
        done < <(comm -13 our-tags.txt upstream-tags.txt)
